#!/usr/bin/env bash

# parses known locations for .desktop files
# written by Nathaniel Maia, June 2018
#
# Modified by Tom van Dijk, now shows (unlocalized) names

# associative array to store paths as basename values
declare -gA PATHS

# check we have required software
if ! hash awk find grep dmenu gtk-launch &>/dev/null; then
    echo -e "ERROR: This script requires: awk find grep dmenu gtk-launch" && exit 1
fi

main() {
    while read -r f; do
        name="$(grep -E "^Name=" "$f" | sed -E 's/^Name=(.*)/\1/')"

        PATHS["$name"]="$f"
    done < <(find -L /usr/share/applications/ $HOME/Desktop \
        ~/.local/share/applications -type f -name '*.desktop')

    local ans="$(for key in "${!PATHS[@]}"; do echo "$key"; done \
        | cat - <(dmenu_path) \
        | uniq \
        | dmenu -H $HOME/.dmenu_drun_histfile "$@")"

    [[ $? != 1 && -n $ans ]] && run "$ans" || return 1
}

run() {
    local cmd
    cmd="${PATHS["$1"]}"

    if [[ "$cmd" ]]; then
        n="$(basename -s .desktop "$cmd")"
        gtk-launch "$n"
    else
        exec "$1"
    fi

    return $?
}

main "$@" &

exit 0
